[CNFT2-1600] [CNFT2-1604] - Page_Info and Page History
CDCgov/NEDSS-Modernization pull request #1001
Opened 2024-02-08 18:03 UTC by lramakr

## Description

[CNFT2-1600] [CNFT2-1604] - Developed Page_Info and Page History

## Tickets

* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-1600, https://cdc-nbs.atlassian.net/browse/CNFT2-1604

## Checklist before requesting a review
- [ ] PR focuses on a single story
- [ ] Code has been fully tested to meet acceptance criteria
- [ ] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [ ] All new functions/classes/components reasonably small
- [ ] Functions/classes/components focused on one responsibility
- [ ] Code easy to understand and modify (clarity over concise/clever)
- [ ] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [ ] PR does not contain hardcoded values (Uses constants)
- [ ] All code is covered by unit or feature tests

2024-02-08 18:33 UTC, rkrusselenq approved these changes

2024-02-08 18:33 UTC, rkrusselenq commented on apps/modernization-ui/src/apps/page-builder/page/management/preview/information/PageInformation.tsx
> +    const { page } = usePageManagement();
can you can the pageId from here?

2024-02-08 18:33 UTC, rkrusselenq commented on apps/modernization-ui/src/apps/page-builder/page/management/preview/information/PageInformation.tsx
> +        const rep: any = await PageInformationService?.getPageHistory?.({
issue: use of any

2024-02-08 18:33 UTC, rkrusselenq commented on apps/modernization-ui/src/apps/page-builder/page/management/preview/information/PageInformation.tsx
> +        });
need to .catch()

2024-02-08 18:39 UTC, mpeels requested changes

2024-02-09 15:49 UTC, lramakr commented on apps/modernization-ui/src/apps/page-builder/page/management/preview/information/PageInformation.tsx
> +    const [totalResults] = useState(4);
Looks like the page-history api missing the pagination details like total no of pages etc.. currently. I tried replicating it by hard coded values. Once the API is fixed, then I will revisit for pagination implementation

2024-02-09 15:49 UTC, mpeels commented on apps/modernization-ui/src/apps/page-builder/page/management/preview/information/PageInformation.tsx
> +    );
Suggestion: `desc` is a required input but there is a check to verify it is not `undefined` (`desc ?? '-'`). I would suggest defining  `desc` as:

```typescript
desc?: string
```

Then you can eliminate the `non-null assertion operator` from:  `pageInfo?.eventType?.name!` and other `renderBlock` calls. The use of the `non-null assertion operator` is typically considered a bad practice as this simply overrides the compilers warning without providing a solution.

2024-02-09 16:06 UTC, mpeels approved these changes

2024-02-09 16:09 UTC, rkrusselenq approved these changes

2024-02-09 16:10 UTC, merged