Cnft1 2016 UI code coverage
CDCgov/NEDSS-Modernization pull request #1005
Opened 2024-02-09 16:12 UTC by hclarkEnq

## Description

Adding code coverage for the UI files using codeCoverageAll properties and utilizing `npm run test:coverageAll` you will get reports for the test coverage across all of the UI folders. There is a specific feature breakdown for feature team 1 on "Search(Event search and patient search)" and "Patient(Profile and Add)". 

## Tickets

* [CNFT1-2016](https://cdc-nbs.atlassian.net/browse/CNFT1-2016)

## Checklist before requesting a review
- [ ] PR focuses on a single story
- [ ] Code has been fully tested to meet acceptance criteria
- [ ] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [ ] All new functions/classes/components reasonably small
- [ ] Functions/classes/components focused on one responsibility
- [ ] Code easy to understand and modify (clarity over concise/clever)
- [ ] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [ ] PR does not contain hardcoded values (Uses constants)
- [ ] All code is covered by unit or feature tests

2024-02-09 17:18 UTC, adamloup-enquizit requested changes
issue (blocker): The `coverage` folder should be added to the [.gitignore](https://github.com/CDCgov/NEDSS-Modernization/blob/main/apps/modernization-ui/.gitignore) for the `modernization-ui`.  A lot of files are created and this will prevent them from being accidentally checked in.

2024-02-09 17:39 UTC, hclarkEnq commented on apps/modernization-ui/package.json
> +        "@jest/globals": "^29.7.0",
will check and test

2024-02-12 15:50 UTC, mpeels approved these changes

2024-02-12 15:51 UTC, mdavis-enquizit approved these changes

2024-02-12 15:58 UTC, merged