Cnft2 1872 data mart repeating number
CDCgov/NEDSS-Modernization pull request #1037
Opened 2024-02-15 21:41 UTC by alaapbharadwaj

## Description

When grouping a subsection, the API needs to accept the Data mart repeat number. This field should be a number from 0-5. 

## Tickets

* [CNFT2-1872](https://cdc-nbs.atlassian.net/browse/CNFT2-1872)

## Checklist before requesting a review
- [ ] PR focuses on a single story
- [ ] Code has been fully tested to meet acceptance criteria
- [ ] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [ ] All new functions/classes/components reasonably small
- [ ] Functions/classes/components focused on one responsibility
- [ ] Code easy to understand and modify (clarity over concise/clever)
- [ ] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [ ] PR does not contain hardcoded values (Uses constants)
- [ ] All code is covered by unit or feature tests

2024-02-15 22:12 UTC, mpeels commented on apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/command/PageContentCommand.java
> +                        Instant requestedOn) implements PageContentCommand {
Suggestion: Formatting seems a bit much here. Ensure you are setting tab size to 2 spaces.

2024-02-15 22:18 UTC, mpeels approved these changes

2024-02-19 15:08 UTC, mpeels approved these changes

2024-02-20 15:44 UTC, sizatenquizit approved these changes

2024-02-20 16:28 UTC, mpeels requested changes
build failure

2024-02-20 20:50 UTC, mpeels approved these changes

2024-02-20 21:02 UTC, sizatenquizit approved these changes

2024-02-20 21:09 UTC, merged