Set target input to dropdown for business rules sections
CDCgov/NEDSS-Modernization pull request #1149
Opened 2024-03-07 21:28 UTC by rkrusselenq

## Description
When adding/editing a business rule and the target type is "subsection" we need to display a drop down with each subsection.  Selecting subsections will in turn select all the questions within that subsection.

Also fixes some behavior related to setting the rule description, and some code cleanup.

## Tickets

* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT2-2148)

## Checklist before requesting a review
- [x] PR focuses on a single story
- [x] Code has been fully tested to meet acceptance criteria
- [x] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [x] All new functions/classes/components reasonably small
- [x] Functions/classes/components focused on one responsibility
- [x] Code easy to understand and modify (clarity over concise/clever)
- [x] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [x] PR does not contain hardcoded values (Uses constants)
- [x] All code is covered by unit or feature tests

2024-03-07 22:18 UTC, alaapbharadwaj requested changes

2024-03-07 22:18 UTC, alaapbharadwaj commented on apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/Add/AddBusinessRule.tsx
> +                console.log('resp', resp);
Issue: console

2024-03-07 22:19 UTC, alaapbharadwaj commented
Question: Will this implementation also take care of not showing empty subsections within the dropdown? Can empty subsections be picked in classic?

2024-03-08 15:05 UTC, rkrusselenq commented
> Question: Will this implementation also take care of not showing empty subsections within the dropdown? Can empty subsections be picked in classic?

good question, hadn't thought of that, i'll see if i can filter them out.

2024-03-08 18:05 UTC, rkrusselenq commented
fixed

2024-03-08 18:16 UTC, alaapbharadwaj requested changes

2024-03-08 18:16 UTC, alaapbharadwaj commented on apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesForm.tsx
> +        // setSourceDescription('');
Issue: comments

2024-03-08 21:29 UTC, mpeels commented
Merge conflict

2024-03-11 14:15 UTC, alaapbharadwaj approved these changes

2024-03-11 14:36 UTC, mpeels approved these changes

2024-03-11 14:53 UTC, merged