CNFT2-1834 Add new tab: 50 char
CDCgov/NEDSS-Modernization pull request #1206
Opened 2024-03-19 19:36 UTC by jlee-enquizit

## Description

Adding 50 char limit to new/edit Tabs.

## Tickets

* [CNFT2-1834](https://cdc-nbs.atlassian.net/browse/CNFT2-1834)

## Checklist before requesting a review
- [x] PR focuses on a single story
- [x] Code has been fully tested to meet acceptance criteria
- [x] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [x] All new functions/classes/components reasonably small
- [x] Functions/classes/components focused on one responsibility
- [x] Code easy to understand and modify (clarity over concise/clever)
- [x] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [x] PR does not contain hardcoded values (Uses constants)
- [x] All code is covered by unit or feature tests

[CNFT2-1834]: https://cdc-nbs.atlassian.net/browse/CNFT2-1834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-03-19 19:39 UTC, mpeels requested changes

2024-03-19 19:39 UTC, mpeels commented on apps/modernization-ui/src/apps/page-builder/services/tabsAPI.ts
> +    console.log('UPDATE', page, request, tabId);
Issue: console.log

2024-03-19 19:39 UTC, mpeels commented on apps/modernization-ui/src/apps/page-builder/page/management/edit/tabs/AddEditTab/AddEditTab.spec.tsx
> +// };
Issue: commented out code

2024-03-19 19:39 UTC, mpeels commented on apps/modernization-ui/src/apps/page-builder/page/management/edit/tabs/ManageTabs/ManageTabs.tsx
> +            console.log('SET', selectedForEdit);
Issue: console.log

2024-03-20 14:59 UTC, mpeels approved these changes

2024-03-20 15:12 UTC, lramakr approved these changes

2024-03-20 16:40 UTC, merged