[CNFT2-2058] [CNFT2-2235] [CNFT2-2244] [CNFT2-2246] - Fix Business Rules Defects
CDCgov/NEDSS-Modernization pull request #1223
Opened 2024-03-22 14:24 UTC by lramakr

## Description

Delete Section and Subsection with confirmation alert.
<img width="1298" alt="Screenshot 2024-03-22 at 7 23 47 AM" src="https://github.com/CDCgov/NEDSS-Modernization/assets/132704359/f854f451-bf42-4fee-b1ac-df992b5a7b1d">
<img width="1221" alt="Screenshot 2024-03-22 at 7 24 20 AM" src="https://github.com/CDCgov/NEDSS-Modernization/assets/132704359/8beb1082-230f-411f-b568-f7dd6a30c0fb">

preview page  - dropdown is editable in preview mode
<img width="1042" alt="Screenshot 2024-03-22 at 10 39 48 AM" src="https://github.com/CDCgov/NEDSS-Modernization/assets/132704359/a2b7fa3d-bc90-419e-b4cd-37fc99dd5bd9">

Datamart fields are not editable for standard question
<img width="1289" alt="Screenshot 2024-03-22 at 10 41 27 AM" src="https://github.com/CDCgov/NEDSS-Modernization/assets/132704359/4dbcd956-84e1-4a97-bb53-21420029d694">

## Tickets

* https://cdc-nbs.atlassian.net/browse/CNFT2-2058
* https://cdc-nbs.atlassian.net/browse/CNFT2-2235
* https://cdc-nbs.atlassian.net/browse/CNFT2-2244
* https://cdc-nbs.atlassian.net/browse/CNFT2-2246

## Checklist before requesting a review
- [ ] PR focuses on a single story
- [x] Code has been fully tested to meet acceptance criteria
- [x] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [x] All new functions/classes/components reasonably small
- [x] Functions/classes/components focused on one responsibility
- [x] Code easy to understand and modify (clarity over concise/clever)
- [x] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [x] PR does not contain hardcoded values (Uses constants)
- [x] All code is covered by unit or feature tests

2024-03-22 14:30 UTC, mpeels submitted a review, later dismissed

2024-03-22 18:38 UTC, jlee-enquizit approved these changes

2024-03-22 19:02 UTC, mpeels requested changes

2024-03-22 19:02 UTC, mpeels commented on apps/modernization-ui/src/apps/page-builder/components/AddQuestion/fields/DataMartFields.tsx
> +    disableWhenStandard?: boolean;
Issue: Updated the story to hide the `DataMartFields` when editing a `standard` question. With that change, no modifications need to be made to the `DataMartFields` component

2024-03-22 19:02 UTC, mpeels commented on apps/modernization-ui/src/apps/page-builder/page/management/edit/edit-question/form/EditPageQuestion.tsx
> +                    />
Suggestion:

```html
{!question?.isStandard && <DataMartFields
                        editing
                        page={page}
                        questionId={question?.id}
                    />}
```

2024-03-25 15:36 UTC, jlee-enquizit approved these changes

2024-03-25 16:09 UTC, merged