CNFT1-2244 Login page: About/Our Vision/Get Involved
CDCgov/NEDSS-Modernization pull request #1296
Opened 2024-04-16 18:51 UTC by jlee-enquizit

## Description

Here we insert the About/Our Vision/Get Involved pages into the WelcomeLayout.
Also small router fix
<img width="1134" alt="image" src="https://github.com/CDCgov/NEDSS-Modernization/assets/124739504/ef574a86-ad6c-483d-a9bc-74c75136de31">

## Tickets

* [CNFT1-2244](https://cdc-nbs.atlassian.net/browse/CNFT1-2244)
* [CNFT1-2262](https://cdc-nbs.atlassian.net/browse/CNFT1-2262)
* [CNFT1-2263](https://cdc-nbs.atlassian.net/browse/CNFT1-2263)

## Checklist before requesting a review
- [ ] PR focuses on a single story
- [x] Code has been fully tested to meet acceptance criteria
- [x] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [x] All new functions/classes/components reasonably small
- [x] Functions/classes/components focused on one responsibility
- [x] Code easy to understand and modify (clarity over concise/clever)
- [x] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [x] PR does not contain hardcoded values (Uses constants)
- [x] All code is covered by unit or feature tests

2024-04-16 21:17 UTC, hclarkEnq commented
question: Should this component design be broken down into components for each subpage? foreseeing potential future changes that might be easier to handle if thats the case, perhaps separating the html structure from the content itself as well?

2024-04-17 14:28 UTC, adamloup-enquizit commented
> question: Should this component design be broken down into components for each subpage? foreseeing potential future changes that might be easier to handle if thats the case, perhaps separating the html structure from the content itself as well?

Good suggestion, smaller single purpose components are easier to maintain.  Also, the number of tabs and their contents are likely to change in the near future.

2024-04-18 17:40 UTC, hclarkEnq submitted a review, later dismissed

2024-04-18 22:00 UTC, adamloup-enquizit requested changes
I'm not sure if those tests are valuable outside of coverage, I get it 😜   

Just noticing that `welcomeLayout` is in the wrong spot, we'll have to move that outside of this PR.

2024-04-19 14:01 UTC, jlee-enquizit commented on apps/modernization-ui/src/welcomeLayout/welcomeRouting.tsx
> +            element: <Landing path="about" />
To maintain consistency for all the different components it ingests.
No good?

2024-04-19 16:12 UTC, adamloup-enquizit approved these changes
🌚<sup> <sup>🚀</sup></sup>

2024-04-19 18:11 UTC, hclarkEnq approved these changes

2024-04-19 21:04 UTC, merged