fixing sortable arrows bg, disbaling field in sex&birth conditionally…
CDCgov/NEDSS-Modernization pull request #1302
Opened 2024-04-18 18:21 UTC by hclarkEnq

Fixing issues related to UI known issues in 
1. Sorting arrows background color -> https://cdc-nbs.atlassian.net/browse/CNFT1-1837
2. Administrative table sorting arrows removal -> https://cdc-nbs.atlassian.net/browse/CNFT1-1835
3. sex and birth field disabled when multiple birth field is selected => "NO" -> https://cdc-nbs.atlassian.net/browse/CNFT1-1729

## Checklist before requesting a review
- [ ] PR focuses on a single story
- [ ] Code has been fully tested to meet acceptance criteria
- [ ] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [ ] All new functions/classes/components reasonably small
- [ ] Functions/classes/components focused on one responsibility
- [ ] Code easy to understand and modify (clarity over concise/clever)
- [ ] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [ ] PR does not contain hardcoded values (Uses constants)
- [ ] All code is covered by unit or feature tests

2024-04-18 18:35 UTC, jlee-enquizit submitted a review, later dismissed

2024-04-19 12:48 UTC, adamloup-enquizit requested changes
The Additional comments columns is still showing the sort button.

![image](https://github.com/CDCgov/NEDSS-Modernization/assets/124325935/8fdbc3bb-ddf1-4c85-8aa3-67363ccbfd0c)

The `AdministrativeTable` also includes sorting code that can also be removed.  Mainly, the `tableHead` state and any associated functions.

2024-04-19 12:48 UTC, adamloup-enquizit commented on apps/modernization-ui/src/apps/patient/profile/sexBirth/SexBirthForm.tsx
> +                                disabled={selectedMultipleBirth === 'N'}
issue:  it's still enabled for "Unknown"

2024-04-19 18:19 UTC, adamloup-enquizit approved these changes
👍 Nice!

2024-04-22 16:45 UTC, jlee-enquizit approved these changes

2024-04-22 18:44 UTC, merged