CNFT1-2198 Segmented Buttons
CDCgov/NEDSS-Modernization pull request #1303
Opened 2024-04-18 18:32 UTC by jlee-enquizit

## Description

Here we create a new SegmentedButtons component to align the styling with our design system.
<img width="602" alt="image" src="https://github.com/CDCgov/NEDSS-Modernization/assets/124739504/df6d2dd0-53e2-40a2-92b0-e4f18278015e">

## Tickets

* [CNFT1-2198](https://cdc-nbs.atlassian.net/browse/CNFT1-2198)
* [CNFT1-2199](https://cdc-nbs.atlassian.net/browse/CNFT1-2199)
* [CNFT1-2200](https://cdc-nbs.atlassian.net/browse/CNFT1-2200)
* [CNFT1-2201](https://cdc-nbs.atlassian.net/browse/CNFT1-2201)

## Checklist before requesting a review
- [ ] PR focuses on a single story
- [x] Code has been fully tested to meet acceptance criteria
- [x] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [x] All new functions/classes/components reasonably small
- [x] Functions/classes/components focused on one responsibility
- [x] Code easy to understand and modify (clarity over concise/clever)
- [x] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [x] PR does not contain hardcoded values (Uses constants)
- [x] All code is covered by unit or feature tests

2024-04-19 20:31 UTC, mpeels requested changes

2024-04-19 20:31 UTC, mpeels commented on apps/modernization-ui/src/components/SegmentedButtons/SegmentedButtons.tsx
> +            {buttons.map((button: any, key: number) => (
Issue: use of `any`

2024-04-19 20:31 UTC, mpeels commented on apps/modernization-ui/src/components/SegmentedButtons/SegmentedButtons.tsx
> +    buttons: any;
Issue: use of any

2024-04-19 20:39 UTC, mpeels commented
https://cdc-nbs.atlassian.net/browse/CNFT1-2200 states the SegmentedButtons should be limited to 2-4 entries.

2024-04-23 14:01 UTC, mpeels submitted a review, later dismissed

2024-04-23 15:17 UTC, adamloup-enquizit commented on apps/modernization-ui/src/components/SegmentedButtons/segmentedButtons.module.scss
> +            border-radius: 0.3rem 0 0 0.3rem;
nit:  The design system specifies a `border-radius` of `0.3125rem`
_this may be the most nit picky review I've ever written_

2024-04-23 15:25 UTC, adamloup-enquizit approved these changes
👍 <sup> 👍 <sup> 👍 </sup></sup>

2024-04-23 15:32 UTC, hclarkEnq approved these changes

2024-04-23 15:45 UTC, mpeels approved these changes

2024-04-23 15:52 UTC, merged