[FIX] addresses sonar issues in testing code
CDCgov/NEDSS-Modernization pull request #1506
Opened 2024-06-28 19:24 UTC by adamloup-enquizit

## Description

Addresses the Sonar issues in test code that were added on [6/26/2024](https://sonarcloud.io/project/issues?resolved=false&id=CDCgov_NEDSS-Modernization) due to a possible configuration change on which files are scanned.

2024-06-28 19:25 UTC, mpeels approved these changes

2024-06-28 19:42 UTC, hclarkEnq submitted a review, later dismissed

2024-06-28 19:49 UTC, mpeels requested changes
failure

2024-06-28 20:54 UTC, hclarkEnq approved these changes

2024-07-01 13:58 UTC, mpeels approved these changes

2024-07-01 15:42 UTC, merged