CNFT1-2434 Patient search: Id field
CDCgov/NEDSS-Modernization pull request #1556
Opened 2024-07-12 19:41 UTC by jlee-enquizit

## Description

Patient search Id field needs to display when Identification Type is selected.

## Tickets

* [CNFT1-2434](https://cdc-nbs.atlassian.net/browse/CNFT1-2434)

## Checklist before requesting a review
- [x] PR focuses on a single story
- [x] Code has been fully tested to meet acceptance criteria
- [x] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [x] All new functions/classes/components reasonably small
- [x] Functions/classes/components focused on one responsibility
- [x] Code easy to understand and modify (clarity over concise/clever)
- [x] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [x] PR does not contain hardcoded values (Uses constants)
- [x] All code is covered by unit or feature tests

2024-07-15 13:56 UTC, mpeels requested changes

2024-07-15 13:56 UTC, mpeels commented on apps/modernization-ui/src/apps/search/patient/PatientCriteria/Id.tsx
>          </div>
Issue: Lacks unit testing

2024-07-15 20:12 UTC, mpeels approved these changes

2024-07-16 13:36 UTC, hclarkEnq approved these changes

2024-07-16 13:48 UTC, merged