Cnft1 2477/investigation list item component
CDCgov/NEDSS-Modernization pull request #1560
Opened 2024-07-15 19:55 UTC by rkrusselenq

## Description

Adds the list item component for investigation search.

Note: as we are trying to push this across the finish line before end of sprint i will have to finish adding unit tests later.
## Tickets

* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT1/boards/112?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT1-2477)

## Checklist before requesting a review
- [x] PR focuses on a single story
- [x] Code has been fully tested to meet acceptance criteria
- [x] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [x] All new functions/classes/components reasonably small
- [x] Functions/classes/components focused on one responsibility
- [x] Code easy to understand and modify (clarity over concise/clever)
- [x] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [x] PR does not contain hardcoded values (Uses constants)
- [x] All code is covered by unit or feature tests

2024-07-15 20:16 UTC, mpeels commented
Can you add a screenshot of the component?

2024-07-16 13:55 UTC, alaapbharadwaj submitted a review, later dismissed

2024-07-16 13:58 UTC, mpeels commented
Issue: Formatting for status state inconsistent with design (border radius)
Design:
![image](https://github.com/user-attachments/assets/5fadab64-49e3-48a6-ade3-02bd33a160c4)

Implementation:
![image](https://github.com/user-attachments/assets/2fac8676-1197-4d24-98eb-3f47d657a4e8)


Issue: Likely inconsistent styling for `No data`. The linked Figma does not have an example but the Lab Report List Item design does

Lab repot design:
![image](https://github.com/user-attachments/assets/764352b7-ec6c-49e4-9cb6-a5410abe81c7)

Implementation:
![image](https://github.com/user-attachments/assets/a98cf386-d347-4be9-b466-5acb85537c3c)

2024-07-16 14:01 UTC, mpeels requested changes
See styling comments above

2024-07-16 15:05 UTC, hclarkEnq approved these changes

2024-07-16 15:06 UTC, merged