CNFT1-2806 Clear all
CDCgov/NEDSS-Modernization pull request #1618
Opened 2024-07-26 20:09 UTC by jlee-enquizit

## Description

Enabling 'Clear all' button in Patient Search, Investigation Search, Lab report search.

## Tickets

* [CNFT1-2806](https://cdc-nbs.atlassian.net/browse/CNFT1-2806)

## Checklist before requesting a review
- [x] PR focuses on a single story
- [x] Code has been fully tested to meet acceptance criteria
- [x] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [x] All new functions/classes/components reasonably small
- [x] Functions/classes/components focused on one responsibility
- [x] Code easy to understand and modify (clarity over concise/clever)
- [x] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [x] PR does not contain hardcoded values (Uses constants)
- [x] All code is covered by unit or feature tests

2024-07-26 20:21 UTC, stevegsa approved these changes

2024-07-26 20:37 UTC, adamloup-enquizit requested changes
The form is already being reset when the search status is being set to `waiting` with a reset.  When "Clear all" is clicked the search results should be cleared, that is not happening any more.  

There are two issues causing this; 

1. The form value is not being passed to down to the component that renders these fields.  
2. The resetting of the form happens when the search status is changed to `waiting`, clicking the "Clear all" button before clicking "Search" the status is going from `waiting` to `waiting` which is not considered a change in react.

2024-07-26 20:52 UTC, jlee-enquizit commented
> The form is already being reset when the search status is being set to `waiting` with a reset. When "Clear all" is clicked the search results should be cleared, that is not happening any more.
> 
> There are two issues causing this;
> 
> 1. The form value is not being passed to down to the component that renders these fields.
> 2. The resetting of the form happens when the search status is changed to `waiting`, clicking the "Clear all" button before clicking "Search" the status is going from `waiting` to `waiting` which is not considered a change in react.

got it!

2024-07-26 22:11 UTC, adamloup-enquizit commented on apps/modernization-ui/src/apps/search/useSearch.ts
> +            dispatch({ type: 'wait' });
Added a status to let the callers know that search is resetting

2024-07-26 22:12 UTC, adamloup-enquizit commented on apps/modernization-ui/src/apps/search/investigation/InvestigationSearch.tsx
>          }
The form only needs to reset when search is resetting.

2024-07-29 18:54 UTC, stevegsa approved these changes

2024-07-30 12:24 UTC, adamloup-enquizit approved these changes

2024-07-30 12:24 UTC, merged