bugs fixed and tests changes as well
CDCgov/NEDSS-Modernization pull request #1643
Opened 2024-08-01 19:51 UTC by alaapbharadwaj

## Description

Fixing bug when clicked on different searches, the result was not resetting to initial banner.

## Tickets

* [CNFT1-2856](https://cdc-nbs.atlassian.net/browse/CNFT1-2856)

## Checklist before requesting a review
- [ ] PR focuses on a single story
- [ ] Code has been fully tested to meet acceptance criteria
- [ ] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [ ] All new functions/classes/components reasonably small
- [ ] Functions/classes/components focused on one responsibility
- [ ] Code easy to understand and modify (clarity over concise/clever)
- [ ] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [ ] PR does not contain hardcoded values (Uses constants)
- [ ] All code is covered by unit or feature tests

2024-08-02 13:01 UTC, adamloup-enquizit requested changes
This is very close just in the wrong spot.  The `TabNavigation` is a base "dumb" component that should not be aware of the context that it's used in.  It's currently only used in the search screens but it's intended to be used anywhere.

Try adding the `useLocation` to the `SearchLayout` and calling `reset` whenever the path changes.  This way you are reacting to a change that happened.

2024-08-06 16:49 UTC, adamloup-enquizit requested changes
Could you revert the changes to `AdvancedSearch.spec.tsx` and `TabNavigation.spec.tsx`?

The rest looks good

2024-08-07 12:28 UTC, adamloup-enquizit approved these changes
👍

2024-08-07 13:28 UTC, hclarkEnq approved these changes

2024-08-07 13:29 UTC, merged