adding fix for local storage saving as table and as list
CDCgov/NEDSS-Modernization pull request #1650
Opened 2024-08-05 15:07 UTC by hclarkEnq

## Description

Fixing bug in saving view type search for local storage in table and list view type preferences

## Tickets

* [CNFT1-2556](https://cdc-nbs.atlassian.net/browse/CNFT1-2556)

## Checklist before requesting a review
- [ ] PR focuses on a single story
- [ ] Code has been fully tested to meet acceptance criteria
- [ ] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [ ] All new functions/classes/components reasonably small
- [ ] Functions/classes/components focused on one responsibility
- [ ] Code easy to understand and modify (clarity over concise/clever)
- [ ] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [ ] PR does not contain hardcoded values (Uses constants)
- [ ] All code is covered by unit or feature tests

2024-08-05 15:14 UTC, stevegsa approved these changes

2024-08-05 16:53 UTC, rkrusselenq submitted a review, later dismissed

2024-08-05 17:41 UTC, adamloup-enquizit reviewed
suggestion:  This is leaking the concern of storing the default settings into another hook.  Try adding a function to the `useSearchSettings` that saves the new local defaults.

2024-08-05 17:43 UTC, adamloup-enquizit requested changes
This is blurring the responsibilities of `useSearchResultDisplay` and `useSettings'.

2024-08-05 20:56 UTC, hclarkEnq commented
> suggestion: This is leaking the concern of storing the default settings into another hook. Try adding a function to the `useSearchSettings` that saves the new local defaults.
Okay will look into this

2024-08-06 16:54 UTC, adamloup-enquizit commented on apps/modernization-ui/src/apps/search/useSearchSettings.ts
> +    }, []);
question:  What is the need for `useCallback` here?

2024-08-06 20:26 UTC, alaapbharadwaj approved these changes

2024-08-06 21:16 UTC, adamloup-enquizit approved these changes
🎈 Looks good

2024-08-06 21:22 UTC, merged