adding add extended data button and updating text in tooltip
CDCgov/NEDSS-Modernization pull request #1662
Opened 2024-08-07 16:00 UTC by hclarkEnq

## Description

UI: Add a button to include Extended data in the Patient data entry form
also fixing a spelling mistake on the tooltip for the gear icon
## Tickets

* [CNFT1-2748](https://cdc-nbs.atlassian.net/browse/CNFT1-2748)

## Checklist before requesting a review
- [ ] PR focuses on a single story
- [ ] Code has been fully tested to meet acceptance criteria
- [ ] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [ ] All new functions/classes/components reasonably small
- [ ] Functions/classes/components focused on one responsibility
- [ ] Code easy to understand and modify (clarity over concise/clever)
- [ ] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [ ] PR does not contain hardcoded values (Uses constants)
- [ ] All code is covered by unit or feature tests

[CNFT1-2748]: https://cdc-nbs.atlassian.net/browse/CNFT1-2748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-08-07 16:51 UTC, jlee-enquizit submitted a review, later dismissed

2024-08-07 16:55 UTC, rkrusselenq submitted a review, later dismissed

2024-08-08 12:36 UTC, adamloup-enquizit requested changes
This cannot be merged without being behind a feature flag, this detail was omitted from the story

2024-08-08 16:43 UTC, adamloup-enquizit approved these changes

2024-08-08 16:58 UTC, merged