adding proper pregnancy status expected values
CDCgov/NEDSS-Modernization pull request #1700
Opened 2024-08-14 16:59 UTC by hclarkEnq

## Description

 Lab reports - Pregnancy status - Revise the spelling of 'Unknonw' fixed.
## Tickets

* [CNFT1-2896](https://cdc-nbs.atlassian.net/browse/CNFT1-2896)

## Checklist before requesting a review
- [ ] PR focuses on a single story
- [ ] Code has been fully tested to meet acceptance criteria
- [ ] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [ ] All new functions/classes/components reasonably small
- [ ] Functions/classes/components focused on one responsibility
- [ ] Code easy to understand and modify (clarity over concise/clever)
- [ ] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [ ] PR does not contain hardcoded values (Uses constants)
- [ ] All code is covered by unit or feature tests

2024-08-14 17:08 UTC, adamloup-enquizit commented
Why is it in all caps?

2024-08-14 17:20 UTC, adamloup-enquizit requested changes
It should be the same as [here](https://github.com/CDCgov/NEDSS-Modernization/blob/90bf900fb7e39848a41a8de402a5671656e683b1/apps/modernization-ui/src/apps/search/investigation/InvestigationFormTypes.ts#L93).  

Please move this list to the `options` folder and reference it in both places.

2024-08-14 17:54 UTC, stevegsa submitted a review, later dismissed

2024-08-15 14:08 UTC, stevegsa approved these changes

2024-08-15 15:30 UTC, adamloup-enquizit approved these changes
👍 Thank for removing duplicated code

2024-08-15 16:00 UTC, merged