Cnft2 2765 data page no table
CDCgov/NEDSS-Modernization pull request #1762
Opened 2024-09-02 03:41 UTC by jlee-enquizit

## Description

Data elements page, no table yet

## Tickets

* [Jira Ticket](url)

## Checklist before requesting a review
- [ ] PR focuses on a single story
- [ ] Code has been fully tested to meet acceptance criteria
- [ ] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [ ] All new functions/classes/components reasonably small
- [ ] Functions/classes/components focused on one responsibility
- [ ] Code easy to understand and modify (clarity over concise/clever)
- [ ] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [ ] PR does not contain hardcoded values (Uses constants)
- [ ] All code is covered by unit or feature tests

2024-09-03 13:51 UTC, mpeels commented
Issue: PR should have target branch `case-dedup-ui`

2024-09-03 16:47 UTC, mpeels requested changes
Should be merged into `case-dedup-ui` branch instead of `main`

2024-09-04 14:22 UTC, rkrusselenq approved these changes

2024-09-04 15:55 UTC, mpeels approved these changes

2024-09-04 17:26 UTC, merged