refactoring administrative ui implementation and removing unneeded styles...
CDCgov/NEDSS-Modernization pull request #1818
Opened 2024-09-16 16:02 UTC by hclarkEnq

refactoring administrative ui implementation and removing unneeded styles...

## Description

Create Inputs for Administrative section with the following fields:
Figma link: https://www.figma.com/design/3BUUZ6e0kGbekLrA77SFDi/NBS-7.x--%3E-Patient-Data-Entry-1.1?node-id=1082-117950&t=GBCBmzaiHTcslpDX-4Connect your Figma account 
Acceptance Criteria
Administrative information as of- This is mandatory field and error has to be displayed when there is no data.

## Tickets

* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-2749)

## Checklist before requesting a review
- [ ] PR focuses on a single story
- [ ] Code has been fully tested to meet acceptance criteria
- [ ] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [ ] All new functions/classes/components reasonably small
- [ ] Functions/classes/components focused on one responsibility
- [ ] Code easy to understand and modify (clarity over concise/clever)
- [ ] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [ ] PR does not contain hardcoded values (Uses constants)
- [ ] All code is covered by unit or feature tests

2024-09-16 16:37 UTC, adamloup-enquizit requested changes
The[ form object](https://github.com/CDCgov/NEDSS-Modernization/blob/6f51c501035967dd5e47709237d674dcc9daf494/apps/modernization-ui/src/apps/patient/add/extended/entry.ts#L15) was defined in [CNFT1-2995](https://github.com/CDCgov/NEDSS-Modernization/pull/1788) and should be used for this page.

2024-09-16 16:37 UTC, adamloup-enquizit commented on apps/modernization-ui/src/apps/patient/add/extended/inputs/administrative/Administrative.tsx
> +import { AdministrativeEntry } from 'apps/patient/profile/administrative/AdministrativeEntry';
You're going to want to use this [AdministrativeEntry](https://github.com/CDCgov/NEDSS-Modernization/blob/main/apps/modernization-ui/src/apps/patient/data/entry.ts#L11) that was created for the new form object.  This also means that we cannot resuse the `AdministrativeEntryFields` component from Patient Profile.  The main reason being the ability to support `Selectable`

2024-09-16 16:37 UTC, adamloup-enquizit commented on apps/modernization-ui/src/apps/patient/add/extended/inputs/administrative/Administrative.tsx
> +    const form = useForm<AdministrativeEntry>({
issue:  This is not a multi-valued area so it's part of the main form.  Only the multi-value entry areas require the sub-form.

2024-09-16 16:37 UTC, adamloup-enquizit commented on apps/modernization-ui/src/apps/patient/add/extended/AddPatientExtendedForm.tsx
> +                                form.setValue('comments', data.comment);
issue:  There is no need to keep two forms in sync, the main form can be used here

2024-09-17 14:37 UTC, adamloup-enquizit requested changes
It looks like there are some left over changes to patient profile that need to be reverted

2024-09-17 14:37 UTC, adamloup-enquizit commented on apps/modernization-ui/src/apps/patient/add/extended/inputs/administrative/Administrative.spec.tsx
> +const mockOnChange = jest.fn();
question:  Is this still needed?

2024-09-17 14:37 UTC, adamloup-enquizit commented on apps/modernization-ui/src/apps/patient/add/extended/inputs/administrative/Administrative.tsx
> +                        <>
question:  was this left in intentionally?

2024-09-17 14:37 UTC, adamloup-enquizit commented on apps/modernization-ui/src/apps/patient/add/extended/inputs/administrative/Administrative.module.scss
> +}
suggestion:  This is going to be common to all of the section in this page and could be it's own component.

2024-09-17 14:37 UTC, adamloup-enquizit commented on apps/modernization-ui/src/apps/patient/profile/administrative/AdministrativeEntryFields.tsx
> -                    required: { value: true, message: 'Comments are required.' },
issue:  revert this change as it affects the patient profile

2024-09-17 14:54 UTC, alaapbharadwaj submitted a review, later dismissed

2024-09-17 16:14 UTC, alaapbharadwaj requested changes

2024-09-17 16:14 UTC, alaapbharadwaj commented on apps/modernization-ui/src/apps/patient/add/extended/inputs/administrative/Administrative.tsx
> +        <Wrapper title="Administrative" id="administrative">
issue: i think the id should be something like "section-Administrative" so the right hand side nav can link to the right section. Check AddPatientExtendedNav.tsx for the exact id value

2024-09-17 16:33 UTC, alaapbharadwaj approved these changes

2024-09-17 19:12 UTC, mpeels approved these changes

2024-09-17 19:15 UTC, alaapbharadwaj approved these changes

2024-09-17 19:37 UTC, adamloup-enquizit approved these changes
👍

2024-09-17 19:43 UTC, merged