Cnft1 3277 UI add patient name column
CDCgov/NEDSS-Modernization pull request #1941
Opened 2024-10-18 13:22 UTC by benlam-ignw

## Description

AC fulfilled: 
User should be able to see Names as a column, in the patient search results table view.
User should see Names as a column in the ‘Column settings’

## Tickets

https://cdc-nbs.atlassian.net/browse/CNFT1-3277

## Checklist before requesting a review
- [ ] PR focuses on a single story
- [ ] Code has been fully tested to meet acceptance criteria
- [ ] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [ ] All new functions/classes/components reasonably small
- [ ] Functions/classes/components focused on one responsibility
- [ ] Code easy to understand and modify (clarity over concise/clever)
- [ ] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [ ] PR does not contain hardcoded values (Uses constants)
- [ ] All code is covered by unit or feature tests

2024-10-18 13:52 UTC, mpeels approved these changes

2024-10-18 15:27 UTC, stevegsa submitted a review, later dismissed

2024-10-18 16:28 UTC, mpeels approved these changes

2024-10-18 17:26 UTC, joeaxcdw commented on apps/modernization-ui/src/apps/search/patient/result/patientSearchResult.tsx
> +                    <div key={index}>
Use the new <ItemGroup> element in design system here. It already has the right CSS styling per the Figma design.

2024-10-18 17:26 UTC, joeaxcdw requested changes
See my comment below

2024-10-18 17:28 UTC, joeaxcdw commented on apps/modernization-ui/src/apps/search/patient/result/patientSearchResult.tsx
> +                    <div key={index}>
Also get latest from main and see `displayOtherNames `function. There is some overlap here.

2024-10-21 13:53 UTC, adamloup-enquizit requested changes
-I think this story was adding the "Patient name" column as a new column leaving the "Legal name" column in place.-

Designs were either changed or they didn't include the "Legal name".

2024-10-21 14:31 UTC, joeaxcdw approved these changes

2024-10-21 14:34 UTC, merged