CNFT1-3305: Add patient other information styling and text issues
CDCgov/NEDSS-Modernization pull request #2078
Opened 2024-12-06 17:09 UTC by joeaxcdw

## Description

Minor fixes to other information section. Current age already fixed in a prior PR. Fix text and styling.

## Tickets

* [Jira Ticket](https://cdc-nbs.atlassian.net/browse/CNFT1-3305)

## Checklist before requesting a review
- [X] PR focuses on a single story
- [X] Code has been fully tested to meet acceptance criteria
- [X] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [X] All new functions/classes/components reasonably small
- [X] Functions/classes/components focused on one responsibility
- [X] Code easy to understand and modify (clarity over concise/clever)
- [X] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [X] PR does not contain hardcoded values (Uses constants)
- [ ] All code is covered by unit or feature tests

2024-12-06 17:47 UTC, stevegsa submitted a review, later dismissed

2024-12-06 21:12 UTC, joeaxcdw commented
Currently investigating padding issues in the search form, not ready for approval yet.

2024-12-09 14:21 UTC, adamloup-enquizit requested changes
The designs for this page changed the layout of the fields from vertical to horizontal and that the cumulative changes would take more than one sprint and we didn't want to have the inconsistent orientation of fields  a new page for "New patient" was created and hidden behind a feature flag.  The "New patient" page was one of the first modernized pages developed, patterns for form entry within the application have evolved since then.

The [new version](https://github.com/CDCgov/NEDSS-Modernization/blob/main/apps/modernization-ui/src/apps/patient/add/basic/AddPatientBasic.tsx) of "New patient" was added a few sprints back and can be accessed from the path `/patient/add`.  This would be the first section added to the [form](https://github.com/CDCgov/NEDSS-Modernization/blob/main/apps/modernization-ui/src/apps/patient/add/basic/AddPatientBasicForm.tsx).

Another reason for the new version of the page was that the current "New patient" form object did not use `Selectable` type, only storing the value.  This resulted in a lot of difficulties when transitioning from this page to the "New patient - extended" page.  A [new form object](https://github.com/CDCgov/NEDSS-Modernization/blob/983506cf0329452ca8da6f0bbd38e65a1dbdf06a/apps/modernization-ui/src/apps/patient/add/basic/entry.ts#L13) was also created for the new version of the page that uses the `Selectable` type to make the transitions more straightforward.  

This had been discussed in many of the refinements for this feature, I am going to make sure this reasoning is added to this story and every other story for the new version of "New patient"

2024-12-09 19:13 UTC, benlam-ignw approved these changes

2024-12-09 19:39 UTC, hclarkEnq approved these changes

2024-12-10 15:23 UTC, merged