CNFT1-1047-The-field-at-path-findAllStateCountyCodeValues-was-declared-as-a-non-null-type-but-the-code-involved-in-retrieving-data-has-wrongly-returned-a-null-value.q
CDCgov/NEDSS-Modernization pull request #278
Opened 2023-06-08 17:57 UTC by JimBarrows-Enquizit

2023-06-09 12:40 UTC, adamloup-enquizit requested changes

2023-06-09 12:40 UTC, adamloup-enquizit commented on apps/modernization-api/src/main/resources/graphql/coded-values.graphqls
> +    findAllStateCountyCodeValues(page: Page): [StateCountyCodeValue!]!
Query definition doesn't match the QueryMapping method.  Is a Page needed here if the results are a list?

2023-06-09 15:15 UTC, stevegsa commented on apps/modernization-api/src/test/resources/features/PatientDataEntryDropDown.feature
> +    Then I get these counties:
Nice!

2023-06-09 15:15 UTC, stevegsa approved these changes

2023-06-12 20:38 UTC, adamloup-enquizit approved these changes

2023-06-13 14:04 UTC, merged