CNFT2-741-Section+SubSection-Update/Delete
CDCgov/NEDSS-Modernization pull request #469
Opened 2023-08-18 08:55 UTC by massad22

2023-08-18 14:26 UTC, mpeels commented on apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/tab/repository/WaUiMetaDataRepository.java
> +    void deletefromTable(Long waUiMetadataUid);
the built in `delete` function should do the same thing

2023-08-18 14:33 UTC, mpeels commented on apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/subsection/SubSectionCreator.java
> +            }
I think we should require both the label and the `visible` values to be present. Then if either are null, throw an exception. Then this becomes something like:

```java
if (request.questionLabel() == null || request.visible() == null) {
    throw new UpdateSubSectionException("Label and visibility fields are required");
}
waUiMetaDataRepository.updateQuestionLabelAndVisibility(request.questionLabel(), request.visible(), request.subSectionId());
return new UpdateSubSectionResponse(request.subSectionId(), "SubSection Updated Successfully");
```

2023-08-18 14:39 UTC, mpeels commented on apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/section/exception/DeleteSectionException.java
> +}
If these new custom exceptions extend either `BadRequestException` or `NotFoundException`, then the `PageBuilderExceptionHandler` will return the "message" to the user and set the appropriate status code on the response.

2023-08-22 20:25 UTC, mpeels requested changes

2023-08-22 20:25 UTC, mpeels commented on apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/section/SectionCreator.java
> +            throw new DeleteSectionException(exception.toString());
I don't believe you can delete a section if it has any questions in it. We would need to verify that the next orderNumber after the section is either: 
1. another section
2. a tab
3. null 

if one of those 3 is true, then we can do the delete, else throw a `DeleteSectionException`

2023-08-22 20:25 UTC, mpeels commented on apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/subsection/SubSectionCreator.java
> +            return new DeleteSubSectionResponse(request.subSectionId(), "Sub Section Deleted Successfully");
I believe the same logic applies here as above, you cannot delete a subsection if it has any content.

so I think the check would be "is the wa_ui_metadata entry with the next order number: "
1. null
2. another subsection
3. another section
4. a tab

if one of those 4 are true, then allow the delete.

2023-08-28 15:15 UTC, mpeels commented on apps/question-bank/src/main/java/gov/cdc/nbs/questionbank/page/content/subsection/SubSectionCreator.java
> +            if(nbsComponentUid == 1010L || nbsComponentUid == 1015L || nbsComponentUid == null || nbsComponentUid == 1016L) {
Similar to above, can we define some constants for these Ids to improve readability?

2023-08-28 17:16 UTC, mpeels approved these changes

2023-08-28 19:05 UTC, massad22 commented
<img width="1188" alt="SectionCreatorTest" src="https://github.com/CDCgov/NEDSS-Modernization/assets/116684885/10ba0759-3269-48d1-b637-7565a38db439">

2023-08-28 19:05 UTC, massad22 commented
<img width="1165" alt="SubSectionControllerTest" src="https://github.com/CDCgov/NEDSS-Modernization/assets/116684885/d2297026-13b1-474c-a2e9-60f7401a5598">

2023-08-28 19:05 UTC, massad22 commented
<img width="1123" alt="SubSectionCreatorTest" src="https://github.com/CDCgov/NEDSS-Modernization/assets/116684885/96be854a-4f20-42e8-ab36-d8e10e58a801">

2023-08-28 19:06 UTC, massad22 commented
<img width="1073" alt="SectionControllerTest" src="https://github.com/CDCgov/NEDSS-Modernization/assets/116684885/50b2e4c7-48ec-425d-b4e3-c74a0368fd15">

2023-08-28 20:50 UTC, merged