disable future selection for date of death field
CDCgov/NEDSS-Modernization pull request #499
Opened 2023-08-29 13:29 UTC by GangulaMounika

2023-08-29 17:02 UTC, adamloup-enquizit requested changes
Using the 'minDate' of the 'DatePicker' does prevent picking future dates from the calendar pop up however, there are inconsistencies in how it handles manual entry.  In add patient the is a 'Please enter valid date' message that is preventing the other validations from occurring.  It's also not aligned with the designs.

We may not be able to use this functionality of the `DatePicker` and have to enforce this via validations.  

There are many validations handled with the [rules from React Hook Form](https://react-hook-form.com/docs/useform/register#options).  There is an example of a custom validation function being used in the [PhoneEmailEntryForm](https://github.com/CDCgov/NEDSS-Modernization/blob/68b62e1cfed064d1140fc03f57b5d5f9cb5cea39/apps/modernization-ui/src/pages/patient/profile/phoneEmail/PhoneEmailEntryForm.tsx#L134)

2023-08-30 19:24 UTC, GangulaMounika commented on apps/modernization-ui/src/components/FormInputs/DatePickerInput.tsx
> +    maxDate?: string;
Unfortunately this maxDate that Datepicker component of truss work takes a string.
I put this as a conditional as not always our custom "DatepickerInput" might need this functionlity.

2023-08-30 19:29 UTC, GangulaMounika commented on apps/modernization-ui/src/pages/addPatient/components/otherInfoFields/OtherInfoFields.tsx
> +    const getCurrentLocalDate = () => {
I agree too, but not all consumers of DatePickerInput might need the same date as the max date. 
We could enhance it at the time such a requirement comes though and go with your suggestion for now. 
Do you think maxDate should be converted into a boolean then and reamed as showMaxDate ?

2023-08-30 20:27 UTC, adamloup-enquizit commented on apps/modernization-ui/src/pages/addPatient/components/otherInfoFields/OtherInfoFields.tsx
> +    const getCurrentLocalDate = () => {
I was thinking that our `DatePickerInput` component could take the maxDate as a `Date` object and internally convert it into the `string` format required by `DatePicker` if it's present.

2023-09-05 15:07 UTC, adamloup-enquizit submitted a review, later dismissed

2023-09-05 21:44 UTC, adamloup-enquizit approved these changes

2023-09-05 23:06 UTC, merged