Merge cnft1 1437 and CNFT1-1456
CDCgov/NEDSS-Modernization pull request #506
Opened 2023-08-30 11:41 UTC by mdavis-enquizit

Cnft1 1437 [Demo] Able to add a new patient with validation error
-added unified validation for errors also.

CNFT1-1456Ensure Event Search Color Consitency in Select Boxes.

2023-08-30 11:43 UTC, mdavis-enquizit commented on apps/modernization-ui/src/components/FormInputs/DatePickerInput.tsx
> +
Could be cleaner but not sure what makes an invalid date. This allows for 1890-2999 year value

2023-08-30 11:44 UTC, mdavis-enquizit commented on apps/modernization-ui/src/pages/addPatient/components/otherInfoFields/OtherInfoFields.tsx
>                              control={control}
This was accidentally overwritten.

2023-08-30 13:23 UTC, adamloup-enquizit requested changes
`OtherInfoFields` has a few lines that are reverting a recent change to the names of the form fields.  

CNFT1-1437 was referring to the `asOf` date field in `GeneralInformation`.  This issue seems to have been resolved in `main` as the issue is not present in the DEV environment.  

Since CNFT-1437 seems to be resolved through other means you can mark that one as done and change this PR to just address CNFT1-1456.  That part looks great.

2023-08-30 13:23 UTC, adamloup-enquizit commented on apps/modernization-ui/src/pages/addPatient/components/otherInfoFields/OtherInfoFields.tsx
> +                            name="dob"
There may have been a few merge conflicts in this file resulting in changes being reverted.  The names of the form properties were aligned with the names expected by the API.  

The `render` property of the [Controller](https://react-hook-form.com/docs/usecontroller/controller) exposes two pretty useful objects `field` and `fieldState`.  

`field` is a render prop that provides state and functions to the component rendering the controlled form field.  The `name` from the `Controller` component is available here which prevents having to make sure that the `Controller` and component have the same name and id's.  

[fieldState](https://react-hook-form.com/docs/useform/getfieldstate) contains `error` and `invalid` properties that are set based on the `rules` from the `Controller`.  This means that the `render` property can provide the error state of the controlled form field without the need to pass down the errors from the `form`.  

`render={({ field: { onChange, value, name }, fieldState:{ error } }) => (` will contain any errors for this field only (if present).  There are a couple of examples of it being used [here](https://github.com/CDCgov/NEDSS-Modernization/blob/665b5074d024f534841898d2fef695add26bf429/apps/modernization-ui/src/pages/patient/profile/addresses/AddressEntryForm.tsx#L74)

2023-08-31 13:45 UTC, adamloup-enquizit approved these changes

2023-08-31 13:46 UTC, adamloup-enquizit reviewed
The Sonar Scan is complaining about a few things.

```
 src/pages/addPatient/components/otherInfoFields/OtherInfoFields.tsx
  Line 17:75:  Replace `,·errors:·any;` with `;·errors:·any`  prettier/prettier
  Line 19:70:  'errors' is defined but never used             @typescript-eslint/no-unused-vars
```

For the prettier issue if you don't have the plugin installed in VS Code it can be formatted from the command line using
`npx prettier --write src/pages/addPatient/components/otherInfoFields/OtherInfoFields.tsx --config ./.prettierrc`

2023-09-05 18:18 UTC, closed without merging

2023-09-05 18:18 UTC, mdavis-enquizit commented
closed for https://github.com/CDCgov/NEDSS-Modernization/pull/522/files