Test file fix
CDCgov/NEDSS-Modernization pull request #511
Opened 2023-08-31 16:24 UTC by lramakr

Test file fix

2023-08-31 17:25 UTC, mpeels commented
Seeing 3 other test failures
1. src/apps/page-builder/components/CreateQuestion/CreateQuestion.spec.tsx:13:16
![image](https://github.com/CDCgov/NEDSS-Modernization/assets/109251240/3e70cdbe-770c-4ca7-8737-daf27ca02be7)
2. src/apps/page-builder/components/CreateCondition/CreateCondition.spec.tsx:56:29
![image](https://github.com/CDCgov/NEDSS-Modernization/assets/109251240/76d9ed6c-2526-4d01-9e54-0ca93315dfc1)
3. src/apps/page-builder/components/CreateCondition/CreateCondition.spec.tsx:38:16
![image](https://github.com/CDCgov/NEDSS-Modernization/assets/109251240/8f95a1dc-0189-4e8b-868f-406167fdc429)

2023-08-31 20:31 UTC, jlee-enquizit approved these changes

2023-08-31 20:34 UTC, jlee-enquizit requested changes
few more test failures

2023-09-07 16:12 UTC, jlee-enquizit approved these changes

2023-09-07 16:33 UTC, merged