CNFT2-1416 Integrate reorder API
CDCgov/NEDSS-Modernization pull request #695
Opened 2023-11-07 17:14 UTC by jlee-enquizit

Here we integrate the reorder API to commit reordering changes to the db

2023-11-07 18:00 UTC, mpeels requested changes

2023-11-07 18:00 UTC, mpeels commented on apps/modernization-ui/src/apps/page-builder/context/DragDropProvider.tsx
> +        reorderObjects(token, Number(destination.droppableId) + (destination.index - 1), moveId, pageDropId);
Question (blocking): Passing `Number(destination.droppableId) + (destination.index - 1)` as the `after` component Id seems wrong. I haven't had my hands on the reorder UI side, but it seems that we would want to get the new index of the drop location.

If thats > 0, get the Id of component at new index - 1.
If drop index == 0, then we want the parent container Id.

If I'm misunderstanding something I may need you to give me a walkthrough of whats going on. I can be easily confused.

2023-11-07 18:00 UTC, mpeels commented on apps/modernization-ui/src/apps/page-builder/pages/EditPage/EditPage.tsx
> +                console.log('DATA', data);
Issue: console.log

2023-11-09 15:41 UTC, mpeels requested changes
Reordering of Section does not seem to work. 
*Note - I did merge main into the branch locally when testing


![reorderBug](https://github.com/CDCgov/NEDSS-Modernization/assets/109251240/40cb7b1a-b158-48f8-875f-67d9d94c69b3)

2023-11-09 18:19 UTC, jlee-enquizit commented
> Reordering of Section does not seem to work. *Note - I did merge main into the branch locally when testing
> 
> ![reorderBug](https://user-images.githubusercontent.com/109251240/281786254-40cb7b1a-b158-48f8-875f-67d9d94c69b3.gif) [ ![reorderBug](https://user-images.githubusercontent.com/109251240/281786254-40cb7b1a-b158-48f8-875f-67d9d94c69b3.gif) ](https://user-images.githubusercontent.com/109251240/281786254-40cb7b1a-b158-48f8-875f-67d9d94c69b3.gif) [ ](https://user-images.githubusercontent.com/109251240/281786254-40cb7b1a-b158-48f8-875f-67d9d94c69b3.gif)

Fixed!

2023-11-13 20:04 UTC, mpeels approved these changes

2023-11-13 22:28 UTC, merged