[CNFT2-1410] Search Target Question
CDCgov/NEDSS-Modernization pull request #711
Opened 2023-11-10 19:14 UTC by lramakr

## Description

Please include a summary of the changes and any key information a reviewer may need.

## Tickets

* [Jira Ticket](url)

## Steps to verify

1. Provide steps here
1.
1.
1.

2023-11-13 16:03 UTC, mpeels commented
This includes code from your other pull requests. Any way we can isolate the commits for the given story to reduce the scope of changes?

2023-11-29 21:13 UTC, achapm requested changes

2023-11-29 21:13 UTC, achapm commented on apps/modernization-ui/src/apps/page-builder/pages/ValuesetLibrary/ValuesetLibraryTable.tsx
> +                    context={useContext(ValueSetsContext)}
We should use createContext and useContext and not need to pass through props:
https://react.dev/learn/passing-data-deeply-with-context

2023-11-29 21:14 UTC, achapm commented on apps/modernization-ui/src/apps/page-builder/pages/QuestionLibrary/QuestionLibraryTable.tsx
> +                    context={useContext(QuestionsContext)}
We should use createContext and useContext and not need to pass through props:
https://react.dev/learn/passing-data-deeply-with-context

2023-12-07 14:32 UTC, achapm requested changes
Please merge with main branch and resolve any conflicts.

2023-12-07 18:45 UTC, lramakr commented
Hi @achapm , @mpeels , 
    The Squash and merge button is not enabled. So I dont see the option to merge. Kindly check

2023-12-11 17:54 UTC, mpeels commented
Closed as this functionality will be split into its own separate story and implementation.

2023-12-11 17:54 UTC, closed without merging