Bug/cnft 1423/add sorting to quick condition modal
CDCgov/NEDSS-Modernization pull request #726
Opened 2023-11-15 16:38 UTC by rkrusselenq

## Description

Adds the ability to sort by column on the quick conditions modal.  Also had to do a little refactoring to keep QuickConditions and ConditionsLibraryTable more DRY
## Tickets

* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT2-1423)

## Steps to verify

1. Navigate to page-builder/manage/pages
2. click Create new page.
3. click "search for condition(s)"
4. Verify sorting by columns works properly.

2023-11-16 16:56 UTC, mpeels reviewed
Question: When clicking a header to sort, the modal shrinks and then grows as the content is removed and then re-added. 

Any good way we can prevent this?
![annoyingSizeChange](https://github.com/CDCgov/NEDSS-Modernization/assets/109251240/4128cc1b-d066-4d46-8f7c-9dd117b4a878)

2023-11-16 18:49 UTC, rkrusselenq commented
> Question: When clicking a header to sort, the modal shrinks and then grows as the content is removed and then re-added.
> 
> Any good way we can prevent this? 

Good catch. I gave it a scroll for the overflow and a fixed height.

2023-11-17 11:01 UTC, mpeels commented
> > Question: When clicking a header to sort, the modal shrinks and then grows as the content is removed and then re-added.
> > Any good way we can prevent this?
> 
> Good catch. I gave it a scroll for the overflow and a fixed height.

Better but now I'm getting double scroll bars :)

![image](https://github.com/CDCgov/NEDSS-Modernization/assets/109251240/9ae7e403-5057-4936-9040-c3750275f3c2)

2023-11-17 17:52 UTC, rkrusselenq commented
> Better but now I'm getting double scroll bars :)
> 

Can't believe i missed that. fixed now.

2023-11-21 21:18 UTC, mpeels requested changes
`Cancel` and `Create new condition` buttons are now inside the table
![image](https://github.com/CDCgov/NEDSS-Modernization/assets/109251240/59bccc77-66c4-423e-91a4-59aa4f9f2150)

2023-11-22 16:13 UTC, rkrusselenq commented
> `Cancel` and `Create new condition` buttons are now inside the table 

Ok sorry had to do some rework but finally got it figured out i think.

2023-11-22 17:08 UTC, mpeels requested changes
Issue: Return of the double scroll bar

![image](https://github.com/CDCgov/NEDSS-Modernization/assets/109251240/e928d919-bce6-4a64-a4bb-45509edd1a36)



Issue: No conditions are selectable. This brings up a requirement that was never implemented. Only conditions that are **NOT** associated with a page should be selectable. So I believe we can update the `asTableRow` to have `selectable: condition.investigationFormCd == undefined,` 

![image](https://github.com/CDCgov/NEDSS-Modernization/assets/109251240/276f99cf-252a-428d-bdf4-5940888a63d6)

2023-11-22 17:08 UTC, mpeels commented on apps/modernization-ui/src/apps/page-builder/components/QuickConditionLookup/QuickConditionLookup.tsx
> +        })
Issue: the `currentPage` starts at 1 and corresponds to what the user sees. The API expects pages to start at 0. I think we need a `currentPage - 1` when performing a search

2023-11-22 17:50 UTC, rkrusselenq commented
> Issue: Return of the double scroll bar
Weird im not seeing it on my screen. I'll keep hacking at it

2023-12-08 22:16 UTC, rkrusselenq commented
Bump

2023-12-18 18:18 UTC, merged