Cnft2 1469 manage tabs drag drop reorder
CDCgov/NEDSS-Modernization pull request #771
Opened 2023-12-06 16:59 UTC by jlee-enquizit

## Description

Here we implement the drag drop reorder functionality to ManageTabs.
The DragDropContext was refactored some to accomodate Tabs but also improve functionality in the Section Reorder Modal.
Some ManageTabs design updates were added to this branch.

## Tickets

* https://cdc-nbs.atlassian.net/browse/CNFT2-1469

## Steps to verify

1. Select a Page from the Page Library
2. Click the `Manage Tabs` button in the Tabs navbar.
3. Drag a tab by the handle and move into a new position.
4. Tab order should update, as well as the Tab order on the Page

2023-12-07 14:19 UTC, achapm requested changes
Please resolve merge conflicts

2023-12-11 13:51 UTC, achapm approved these changes
Please see the comments below, otherwise 👍

2023-12-11 13:51 UTC, achapm commented on apps/modernization-ui/src/styles/_uswds.scss
> +    // display: flex;
Unless you see a good reason to keep this, we should remove the comments here and the line below. Its just adding cruft.

2023-12-11 14:44 UTC, jlee-enquizit commented on apps/modernization-ui/src/apps/page-builder/pages/EditPage/ReorderSubsection/ReorderSubsection.tsx
> +                    <div className={`reorder-subsection__questions ${!questionsOpen ? 'closed' : ''}`}>
looks okay here

2023-12-12 18:19 UTC, mpeels approved these changes

2023-12-12 18:19 UTC, merged