[CNFT2-1582] - Search Value set
CDCgov/NEDSS-Modernization pull request #816
Opened 2023-12-19 15:03 UTC by lramakr

## Description

Developed Search Value set

## Tickets

* [Jira Ticket] https://cdc-nbs.atlassian.net/browse/CNFT2-1582

## Checklist before requesting a review
- [ ] PR focuses on a single story
- [ ] Code has been fully tested to meet acceptance criteria
- [ ] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [ ] All new functions/classes/components reasonably small
- [ ] Functions/classes/components focused on one responsibility
- [ ] Code easy to understand and modify (clarity over concise/clever)
- [ ] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [ ] PR does not contain hardcoded values (Uses constants)
- [ ] All code is covered by unit or feature tests

2023-12-20 22:06 UTC, mpeels commented
1. Has the design team signed off on the existing `ValueSetLibrary` component?
2. Similar to the `QuestionLibrary`, I was expecting it to only appear in a modal and therefore not need a route. Is this correct?

2023-12-21 16:49 UTC, lramakr commented
Yes Mike. 
There are 2 scenario. 
1. The question Library opens from left side nav where you dont see the checkboxes to select that row and add to page where it opens in the page itself
2. The question library opens from Add Question on edit page and it has the check boxes to select it to add to page and this open in the modal. I have added the route for this scenario.

2023-12-26 15:36 UTC, mpeels commented
> Yes Mike. There are 2 scenario.
> 
> 1. The question Library opens from left side nav where you dont see the checkboxes to select that row and add to page where it opens in the page itself
> 2. The question library opens from Add Question on edit page and it has the check boxes to select it to add to page and this open in the modal. I have added the route for this scenario.

Scenario #1 is not currently in scope. The left side nav always routes to Classic NBS. First the first iteration of Page Builder only scenario 2 is valid.

2024-01-02 21:33 UTC, alaapbharadwaj requested changes

2024-01-02 21:33 UTC, alaapbharadwaj commented on apps/modernization-ui/src/apps/page-builder/pages/ValuesetLibrary/ValuesetLibraryTable.tsx
Issue(blocking): in line 41 an authorization const is created, could use the `authorization()` that is imported in

2024-01-02 21:33 UTC, alaapbharadwaj commented on apps/modernization-ui/src/apps/page-builder/pages/ValuesetLibrary/useValuesetAPI.ts
> +                      // valueSetCode: ''
Question: Will this comment be used in the future? Or can it be removed?

2024-01-02 21:34 UTC, mpeels requested changes

2024-01-02 21:34 UTC, mpeels commented on apps/modernization-ui/src/routes/AppRoutes.tsx
> +                                            <Route path="valueset-library" element={<ValuesetLibrary />} />
Issue: Value set library should only be accessible from within a modal during the create question flow.

2024-01-02 21:34 UTC, mpeels commented on apps/modernization-ui/src/apps/page-builder/generated/models/ValueSet.ts
> +    valueSetName?: string;
Question: I see changes to a `generated` file but no changes to the API. Was this re-generated based on changes from another PR or were these changes applied manually?

2024-01-10 20:59 UTC, mpeels commented
temporarily closing this PR as this has been de-prioritized until completion of all create question functionality

2024-01-10 20:59 UTC, closed without merging