Patient Profile moved from pages to apps module
CDCgov/NEDSS-Modernization pull request #822
Opened 2023-12-19 22:35 UTC by mdavis-enquizit

## Description

The code base is aiming to align with the organization in terms of features so that each feature can be approached individually and featured by package, specifically Changing folder structure to add patient profile features within the apps folder.

## Tickets

* [CNFT1-1773](https://cdc-nbs.atlassian.net/browse/CNFT1-1773)

## Checklist before requesting a review
- [ ] PR focuses on a single story
- [ ] Code has been fully tested to meet acceptance criteria
- [ ] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [ ] All new functions/classes/components reasonably small
- [ ] Functions/classes/components focused on one responsibility
- [ ] Code easy to understand and modify (clarity over concise/clever)
- [ ] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [ ] PR does not contain hardcoded values (Uses constants)
- [ ] All code is covered by unit or feature tests

2023-12-20 18:41 UTC, adamloup-enquizit requested changes
Demographics.tsx, Events.tsx, and Summary.tsx should be moved to `apps/patient/profile`

2023-12-21 16:16 UTC, GangulaMounika approved these changes

2023-12-21 16:17 UTC, hclarkEnq approved these changes

2023-12-21 17:15 UTC, GangulaMounika requested changes

2023-12-21 17:15 UTC, GangulaMounika commented on apps/modernization-ui/src/apps/patient/profile/Demographics.tsx
> -import { IdentificationsTable } from 'pages/patient/profile/identification';
This should be under the components folder under the patient
That is how the page builder is. 

Under the apps folder's app we should have the component, models and all other folders. There is where we need to add these files.

2023-12-21 18:51 UTC, hclarkEnq approved these changes

2023-12-21 22:47 UTC, adamloup-enquizit approved these changes

2023-12-21 23:04 UTC, merged