CNFT2-1575-delete-static-element
CDCgov/NEDSS-Modernization pull request #837
Opened 2023-12-26 14:28 UTC by alaapbharadwaj

## Description

As a PB user, I want to deleted a static question when needed. 

## Tickets

* [CNFT2-1575](https://cdc-nbs.atlassian.net/browse/CNFT2-1575)

## Checklist before requesting a review
- [ ] PR focuses on a single story
- [ ] Code has been fully tested to meet acceptance criteria
- [ ] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [ ] All new functions/classes/components reasonably small
- [ ] Functions/classes/components focused on one responsibility
- [ ] Code easy to understand and modify (clarity over concise/clever)
- [ ] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [ ] PR does not contain hardcoded values (Uses constants)
- [ ] All code is covered by unit or feature tests

2023-12-26 18:03 UTC, mpeels requested changes

2023-12-26 18:03 UTC, mpeels commented on apps/modernization-ui/src/apps/page-builder/page/management/edit/staticelement/AddStaticElement.spec.tsx
> +}
Suggestion: Can mock functions using `jest.fn()`. Can then assert that they are called when expected

2023-12-26 18:03 UTC, mpeels commented on apps/modernization-ui/src/apps/page-builder/page/management/edit/subsection/Subsection.tsx
> +    console.log(subsection.questions);
Issue: console.log

2023-12-26 22:41 UTC, mpeels approved these changes

2023-12-27 15:17 UTC, lramakr approved these changes

2023-12-27 15:17 UTC, merged