adding totalResults to the aria label and setting the data to load sooner for screen readers
CDCgov/NEDSS-Modernization pull request #906
Opened 2024-01-17 18:30 UTC by hclarkEnq

## Description

This pr is designed to fix an issue where screen readers were not able to load the data associated with the "Results for" label when it is focused upon making a search. Now for each time there is a search made the screen reader should read the data found in the label associated with the search just made, for example: "5 Results for lastName: s" . 
Also I added an aria-label to include the totalResults found associated with the search just.

## Tickets

* [SSTT-1844](https://cdc-nbs.atlassian.net/browse/CNFT1-1844)

## Checklist before requesting a review
- [ ] PR focuses on a single story
- [ ] Code has been fully tested to meet acceptance criteria
- [ ] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [ ] All new functions/classes/components reasonably small
- [ ] Functions/classes/components focused on one responsibility
- [ ] Code easy to understand and modify (clarity over concise/clever)
- [ ] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [ ] PR does not contain hardcoded values (Uses constants)
- [ ] All code is covered by unit or feature tests

2024-01-17 18:43 UTC, adamloup-enquizit requested changes

2024-01-17 18:43 UTC, adamloup-enquizit commented on apps/modernization-ui/src/apps/search/advancedSearch/AdvancedSearch.tsx
> +                                    aria-label={resultTotal + ' amount of results have been found'}
suggestion: The `aria-label` message is a little confusing and should match what's displayed more.  `X Results for..` is displayed, should the message be similar? `X Results have been found`

2024-01-17 20:11 UTC, mdavis-enquizit approved these changes

2024-01-19 13:59 UTC, adamloup-enquizit approved these changes
👍

2024-01-19 14:16 UTC, merged