CNFT2-1704 Edit page: Add Tab
CDCgov/NEDSS-Modernization pull request #917
Opened 2024-01-19 20:23 UTC by jlee-enquizit

## Description

Here we create the button and modal to Manage Tabs. The button appears in the tab bar in Edit mode. The modal will have other functionality in subsequent tickets. For now, you can click Add new tab to bring up the form to add. An alert pops up upon success and the page underneath refreshs the tabs.

## Tickets

[* [Jira Ticket](url)](https://cdc-nbs.atlassian.net/browse/CNFT2-1704)

## Checklist before requesting a review
- [ ] PR focuses on a single story
- [x] Code has been fully tested to meet acceptance criteria
- [x] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [x] All new functions/classes/components reasonably small
- [x] Functions/classes/components focused on one responsibility
- [x] Code easy to understand and modify (clarity over concise/clever)
- [x] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [x] PR does not contain hardcoded values (Uses constants)
- [x] All code is covered by unit or feature tests

2024-01-19 22:11 UTC, mpeels requested changes

2024-01-19 22:11 UTC, mpeels commented on apps/modernization-ui/src/apps/page-builder/page/management/header/tabs/PageTabs.tsx
> +export const PageTabs = ({ pageId, tabs, onAddSuccess }: Props) => {
Issue: The `PageTabs` component is used in the `PageHeader`, this is included in both the `Edit` and `Preview` pages. Management features will not be available in the Preview mode.

I don't like adding the manage tabs functionality to this component and would rather have a separate `ManageTab` component that renders just the `Manage tabs` text and handles all of the required logic. That way the `PageTabs` can still be a simple list renderer with onClick handlers.

This new component can then be added to the `PageHeader` and conditionally rendered if editing is enabled. May have to have an optional prop on the `PageHeader` to allow enabling the editing.

2024-01-19 22:11 UTC, mpeels commented on apps/modernization-ui/src/apps/page-builder/page/management/header/tabs/PageTabs.tsx
> +                        <h4>Manage tabs</h4>
Issue: we should avoid using `h` tags unless we are specifying a header over a body of text. a `Heading` component exists that accepts a `level` prop that will provide the styling.

2024-01-19 22:11 UTC, mpeels commented on apps/modernization-ui/src/apps/page-builder/page/management/header/tabs/page-tabs.module.scss
> +        background-color: pink;
Issue: we should leverage colors in the `styles/_colors`. If an appropriate color is not in the stylesheet already, the design team should be consulted to determine if the figma used an incorrect color by accident.

2024-01-22 15:45 UTC, mpeels approved these changes

2024-01-22 16:03 UTC, lramakr approved these changes

2024-01-22 16:11 UTC, merged