Fix styling for business rules library/add/edit form
CDCgov/NEDSS-Modernization pull request #927
Opened 2024-01-24 01:42 UTC by rkrusselenq

## Description

This was left over styling from CNFT2-1598.  Addresses most styling issues that were left behind, some minor cosmetics still remain.

## Tickets

* [Jira Ticket](https://cdc-nbs.atlassian.net/jira/software/c/projects/CNFT2/boards/99?assignee=712020%3A591f5469-427d-49e9-87dc-8b4df72a02b4&selectedIssue=CNFT2-1598)

## Checklist before requesting a review
- [ x] PR focuses on a single story
- [ x] Code has been fully tested to meet acceptance criteria
- [ x] PR is reasonably small and reviewable (Generally less than 10 files and 500 changed lines)
- [ x] All new functions/classes/components reasonably small
- [x ] Functions/classes/components focused on one responsibility
- [ x] Code easy to understand and modify (clarity over concise/clever)
- [ x] PRs containing TypeScript follow the [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html)
- [ x] PR does not contain hardcoded values (Uses constants)
- [ x] All code is covered by unit or feature tests

2024-01-24 14:53 UTC, mpeels requested changes

2024-01-24 14:53 UTC, mpeels commented on apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibrary.tsx
> +            <PageBuilder page="pages">
Suggestion: I would recommend removing the use of the `<PageBuilder>` element. It was used in the old `EditPage` and will probably be removed soon*.

2024-01-24 15:04 UTC, alaapbharadwaj requested changes

2024-01-24 21:34 UTC, mpeels commented on apps/modernization-ui/src/apps/page-builder/pages/BusinessRulesLibrary/BusinessRulesLibraryTable.tsx
> +        console.log('name', name);
issue: console.log

2024-01-24 21:47 UTC, mpeels submitted a review, later dismissed

2024-01-25 18:54 UTC, jlee-enquizit approved these changes

2024-01-25 19:04 UTC, mpeels approved these changes

2024-01-25 19:08 UTC, merged